{% set name = "pyproject2conda" %}
{% set version = "0.17.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject2conda-{{ version }}.tar.gz
  sha256: e1abc3a3ac1e8df47d5226b74dea883f877cc023ee48b7cd2111f9574c91f110

build:
  entry_points:
    - p2c = pyproject2conda.cli:app
    - pyproject2conda = pyproject2conda.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - tomli
    - typer
    - typing_extensions

test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
    - p2c --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary:
    A script to convert a Python project declared on a pyproject.toml to a conda
    environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
