{% set name = "pyproject2conda" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject2conda-{{ version }}.tar.gz
  sha256: fa1dfd4ac2ac703878316de0185ea710fd2ef80be09b2ad7e9ff16096df11266

build:
  entry_points:
    - p2c = pyproject2conda.cli:app
    - pyproject2conda = pyproject2conda.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.14
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8,<3.14
    - packaging
    - tomli
    - typer
    - typing_extensions

test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
    - p2c --help
  requires:
    - pip

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary:
    A script to convert a Python project declared on a pyproject.toml to a conda
    environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
