{% set name = "pyproject2conda" %}
{% set version = "0.19.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4b/e3/0e66e02b92a0044fac9e8064f3fbd90e639f450690bc2d873305462170d4/pyproject2conda-{{ version }}.tar.gz
  sha256: e9ccf3a2272119f01dbbace67735bb924fd7f4a01dd082e90f055c5ac0e0c138

build:
  entry_points:
    - p2c = pyproject2conda.cli:app
    - pyproject2conda = pyproject2conda.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - tomli
    - typer
    - typing_extensions

test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
    - p2c --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary: A script to convert a Python project declared on a pyproject.toml to a conda environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
